name: fetch repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo list kd-collective --limit 1000 --fork --json nameWithOwner --jq '.[].nameWithOwner' | xargs -n1 gh repo sync
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGE }}

  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh repo list kd-collective --limit 1000 --fork --json nameWithOwner  --jq '.[].nameWithOwner' | sort | sed 's/\(.*\)/- https:\/\/github.com\/\1/' > README.md
          sed -i "1i## `date`\n" README.md
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGE }}
